[package]
name = "approx_int"
version = "1.0.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[lib]
doctest = false
